[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "static"]

[tasks.serve]
command = "simple-http-server"
args = ["-i", "./", "-p", "3000", "--nocache", "--try-file", "index.html"]